# Generated by Django 4.2.10 on 2024-05-09 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0093_alter_publiccontact_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="all_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, null=True, size=None
            ),
        ),
    ]
