name: Issue
description: Capture uncategorized work or content

body:
  - type: markdown
    id: help
    attributes:
      value: |
        > Titles should be short, descriptive, and compelling.
  - type: textarea
    id: issue
    attributes:
      label: Issue description and context
      description: |
        Describe the issue so that someone who wasn't present for its discovery can understand the problem and why it matters. Use full sentences, plain language, and good [formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax – links and images welcome! Share desired outcomes or potential next steps.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: "If known, share 1-3 statements that would need to be true for this issue to be considered resolved. Use a checklist."
  - type: textarea
    id: issue-links
    attributes:
      label: Other issues
      description: |
        Add the issue number of other issues this relates to and how.
        
        Example:
        - 🚧 Blocks/is blocked by #123
        - 🔄 Relates to #234
