name: Issue
description: Describe an idea, feature, content, or non-bug finding

body:
  - type: markdown
    id: title-help
    attributes:
      value: |
        > Titles should be short, descriptive, and compelling.
  - type: textarea
    id: issue-description
    attributes:
      label: Issue description and context
      description: |
        Describe the issue so that someone who wasn't present for its discovery can understand the problem and why it matters. Use full sentences, plain language, and good [formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Share desired outcomes or potential next steps. Images or links to other content/context (like documents or Slack discussions) are welcome.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: "If known, share 1-3 statements that would need to be true for this issue to be considered resolved. Use a [task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists) if appropriate."
  - type: textarea
    id: links-to-other-issues
    attributes:
      label: Links to other issues
      description: |
        Add the issue #number of other issues this relates to and how (e.g., 🚧 Blocks, ⛔️ Is blocked by, 🔄 Relates to).
      placeholder: 🔄 Relates to... 
  - type: markdown
    id: note
    attributes:
      value: |
        > We may edit this issue's text to document our understanding and clarify the product work.
