name: Issue
description: Capture uncategorized work or content

body:
  - type: markdown
    id: help
    attributes:
      value: |
        > **Note**
        > GitHub Issues use [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for formatting.
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: |
        Describe the issue you are adding or content you are suggesting.
        Share any next steps that should be taken our outcomes that would be beneficial.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: "Include additional references (screenshots, design links, documentation, etc.) that are relevant"
  - type: textarea
    id: issue-links
    attributes:
      label: Issue Links
      description: |
        What other issues does this story relate to and how?
        
        Example:
        - 🚧 Blocked by: #123
        - 🔄 Relates to: #234