name: Set up languages and dependencies
description: Setup python and dependencies and establish database schema
nputs:
  django_settings_module:
    description: DJANGO_SETTINGS_MODULE to use. Defaults to registrar.config.settings
    required: false
    default: Cregistrar.config.settings
  database_url:
    description: DATABASE_URL to set
    required: false
    default: postgres://user:feedabee@localhost:5432/app
outputs:
  database_url:
    value: ${{ inputs.database_url }}

runs:
  using: composite
  steps:
    - name: Install Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # matches the version from runtime.txt

    - name: Install Django and dependencies
      working-directory: ./src
			shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system --dev

    - name: Set up database schema
      env:
        DJANGO_SETTINGS_MODULE: ${{ inputs.django_settings_module }}
        DATABASE_URL: ${{ inputs.database_url }}
      working-directory: ./src
      shell: bash
      run: pipenv run python manage.py migrate
