version: "3.0"
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    links:
      - db
    working_dir: /app
    entrypoint: python /app/docker_entrypoint.py
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      # Send stdout and stderr straight to the terminal without buffering
      - PYTHONUNBUFFERED=yup
      # How to connect to Postgre container
      - DATABASE_URL=postgres://user:feedabee@db/app
      # Tell Django where to find its configuration
      - DJANGO_SETTINGS_MODULE=registrar.config.settings
      # Set a local key for Django
      - DJANGO_SECRET_KEY=feedabee
      # Run Django in debug mode on local
      - DJANGO_DEBUG=True
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    # command: "python"
    command: >
      bash -c " python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8080"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=feedabee

  pa11y:
    build:
      context: .
      dockerfile: node.Dockerfile
    cap_add:
      - SYS_ADMIN
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    links:
      - app
    profiles:
      - pa11y
