version: "3.0"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    links:
      - db
    working_dir: /app
    entrypoint: python /app/docker_entrypoint.py
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      # Ensure stdout and stderr are sent straight to the terminal without buffering
      - PYTHONUNBUFFERED=yup
      # In case we'd like to know
      - RUNNING_IN_DOCKER=yup
      # How to connect to Postgre container
      - DATABASE_URL=postgres://user:feedabee@db/app
      # Run in development mode on our local
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    command: "python"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=feedabee
