name: Upload current-full.csv and current-federal.csv

on:
  schedule:
    # Runs every day at 5 AM UTC
    - cron: '0 5 * * *'


jobs:
  upload_reports:
    runs-on: ubuntu-latest
    env:
      CF_USERNAME: CF_${{ github.event.inputs.environment }}_USERNAME
      CF_PASSWORD: CF_${{ github.event.inputs.environment }}_PASSWORD
    steps:
      - uses: actions/checkout@v3

      - name: Install CF CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
          sudo mv cf /usr/local/bin

      - name: Generate current-federal.csv
        run: cf run-task getgov-za "/tmp/lifecycle/shell -c './manage.py generate_current_full_report.py'"
        
      
      - name: Generate current-full.csv
        run: cf run-task getgov-za "/tmp/lifecycle/shell -c './manage.py generate_current_federal_report.py'"
