name: Upload current-full.csv and current-federal.csv
run-name: Upload current-full.csv and current-federal.csv for branch ${{ github.head_ref }}

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment do you wish to load reports for?
        options:
          - stable
          - staging
          - development
          - ky
          - es
          - nl
          - rh
          - za
          - gd
          - rb
          - ko
          - ab
          - bl
          - rjm
          - dk
  # TODO - uncomment after #1403 is finished
  #schedule:
    # Runs every day at 5 AM UTC.
    # - cron: "0 5 * * *"

jobs:
  variables: 
    outputs:
      environment: ${{ steps.var.outputs.environment }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Setting global variables
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            const environment = (github && github.event && github.event.inputs) ? github.event.inputs.environment : 'za';
            core.setOutput('environment', environment);

  upload-reports:
    runs-on: ubuntu-latest
    needs: [variables]
    env:
      CF_USERNAME: CF_{{ needs.variables.outputs.environment }}_USERNAME
      CF_PASSWORD: CF_{{ needs.variables.outputs.environment }}_PASSWORD
    steps:
      - name: Generate current-federal.csv
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets[env.CF_USERNAME] }}
          cf_password: ${{ secrets[env.CF_PASSWORD] }}
          cf_org: cisa-dotgov
          cf_space: ${{ needs.variables.outputs.environment }}
          full_command: "cf run-task getgov-${{ needs.variables.outputs.environment }} --command 'python manage.py generate_current_federal_report' --name federal"

      - name: Generate current-full.csv
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets[env.CF_USERNAME] }}
          cf_password: ${{ secrets[env.CF_PASSWORD] }}
          cf_org: cisa-dotgov
          cf_space: ${{ needs.variables.outputs.environment }}
          full_command: "cf run-task getgov-${{ needs.variables.outputs.environment }} --command 'python manage.py generate_current_full_report' --name full"

