name: Upload current-full.csv and current-federal.csv
run-name: Upload current-full.csv and current-federal.csv for branch ${{ github.head_ref }}

on:
  pull_request:
  schedule:
    # Runs every day at 5 AM UTC.
    - cron: "0 5 * * *"

jobs:
  default:
    outputs:
      default: CF_REPORT_ENV

  variables:
    needs: [default]
    env:
      CF_DEFAULT: $ {{ needs.default.outputs.default }}
    outputs:
      environment: ${{ steps.var.outputs.environment}}
    runs-on: "ubuntu-latest"
    steps:
      - name: Setting global variables
        uses: actions/github-script@v6
        id: var
        with:
          script: |
            const environment = ${{ secrets[env.CF_DEFAULT] }};
            core.setOutput("environment", environment);

  upload-reports:
    runs-on: ubuntu-latest
    needs: [variables]
    env:
      CF_USERNAME: CF_${{ needs.variables.outputs.environment }}_USERNAME
      CF_PASSWORD: CF_${{ needs.variables.outputs.environment }}_PASSWORD
      CF_DEFAULT_ENV: CF_REPORT_ENV
    steps:
      - name: Generate current-federal.csv
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets[env.CF_USERNAME] }}
          cf_password: ${{ secrets[env.CF_PASSWORD] }}
          cf_org: cisa-dotgov
          cf_space: ${{ needs.variables.outputs.environment }}
          cf_command: "run-task getgov-${{ needs.variables.outputs.environment }} --command 'python manage.py generate_current_federal_report' --name federal"

      - name: Generate current-full.csv
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets[env.CF_USERNAME] }}
          cf_password: ${{ secrets[env.CF_PASSWORD] }}
          cf_org: cisa-dotgov
          cf_space: ${{ needs.variables.outputs.environment }}
          cf_command: "run-task getgov-${{ needs.variables.outputs.environment }} --command 'python manage.py generate_current_full_report' --name full"

