name: Build and deploy

# This workflow runs on pushes to main (typically,
# a merged pull request) and on pushes of tagged commits.

# Pushes to main will deploy to Staging

on:
  push:
    branches:
      - main

    tags:
      - v*

  workflow_dispatch:

jobs:
  deploy-staging:
    # if this job runs on a branch, we deduce that code
    # has been pushed to main and should be deployed to staging
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile USWDS assets
        working-directory: ./src
        run: |
          docker compose run node npm install && 
          docker compose run node npx gulp copyAssets &&
          docker compose run node npx gulp compile 
      - name: Collect static assets 
        working-directory: ./src
        run: docker compose run app python manage.py collectstatic
      - name: Deploy to cloud.gov sandbox
        uses: 18f/cg-deploy-action@main
        env:
          DEPLOY_NOW: thanks
        with:
          cf_username: ${{ secrets.CF_STAGING_USERNAME }}
          cf_password: ${{ secrets.CF_STAGING_PASSWORD }}
          cf_org: cisa-getgov-prototyping
          cf_space: staging
          push_arguments: "-f ops/manifests/manifest-staging.yaml"
