name: Build and deploy

# This workflow runs on pushes to main (typically,
# a merged pull request) and on pushes of tagged commits.

# Pushes to main will deploy to Unstable; tagged commits
# will deploy to Staging

on:
  push:
    branches:
      - main

    tags:
      - v*

  workflow_dispatch:

jobs:
  deploy-unstable:
    # if this job runs on a branch, we deduce that code
    # has been pushed to main and should be deployed to unstable
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to cloud.gov sandbox
        uses: 18f/cg-deploy-action@main
        env:
          DEPLOY_NOW: thanks
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: sandbox-gsa
          cf_space: dotgov-poc
          push_arguments: "-f ops/manifests/manifest-unstable.yaml"

  # deploy-staging:
  #   # if this job runs on a tag, we deduce that code
  #   # has been tagged for release and should be deployed to staging
  #   if: ${{ github.ref_type == 'tag' }}
