name: Run migrations

# This workflow can be run from the CLI
#     gh workflow run migrate.yaml -f environment=sandbox
# OR
#     cf run-task getgov-staging --wait \
#        --command 'python manage.py migrate' --name migrate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Where should we run migrations
        options:
        - staging

jobs:
  migrate-staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Django migrations for staging
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_STAGING_USERNAME }}
          cf_password: ${{ secrets.CF_STAGING_PASSWORD }}
          cf_org: cisa-getgov-prototyping
          cf_space: staging
          full_command: "cf run-task getgov-staging --wait --command 'python manage.py migrate' --name migrate"

