name: Run migrations

# This workflow can be run from the CLI
#     gh workflow run migrate.yaml -f environment=sandbox
# OR
#     cf run-task getgov-stable --wait \
#        --command 'python manage.py migrate' --name migrate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Where should we run migrations
        options:
        - stable

jobs:
  migrate-stable:
    if: ${{ github.event.inputs.environment == 'stable' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Django migrations for stable
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_STABLE_USERNAME }}
          cf_password: ${{ secrets.CF_STABLE_PASSWORD }}
          cf_org: cisa-getgov-prototyping
          cf_space: stable
          full_command: "cf run-task getgov-stable --wait --command 'python manage.py migrate' --name migrate"

