# test.yml
name: Testing

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Linting
        working-directory: ./src
        # all of our linting is configured in
        # registrar/management/commands/lint.py
        run: docker compose run app python manage.py lint

  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        working-directory: ./src
        run: docker compose run app python manage.py test

  pa11y-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Disable Login
        working-directory: ./src
        # by adding MockUserLogin to settings.MIDDLEWARE
        run: |
          perl -pi \
          -e 's/"csp.middleware.CSPMiddleware",/$&"registrar.tests.common.MockUserLogin",/' \
          src/registrar/config/settings.py

      - name: Accessibility Scan
        working-directory: ./src
        # leverage the docker compose setup that we already have for local development
        run: docker compose run pa11y npm run pa11y-ci
