# test.yml
name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  python-linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install bandit black flake8 mypy types-requests
      - name: Lint with flake8
        working-directory: ./src
        run: flake8 . --count --max-complexity=10  --show-source --statistics --max-line-length=120
      - name: Check formatting with black
        working-directory: ./src
        run: black --check .
      - name: Run bandit
        working-directory: ./src
        run: bandit -r .
      - name: Run type checking
        working-directory: ./src
        run: mypy .
